/****** Object:  Table [dbo].[AUX_TABLE]    Script Date: 11/24/2019 1:25:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUX_TABLE](
	[MT_KEY1] [nvarchar](128) NOT NULL,
	[MT_KEY2] [bigint] NOT NULL,
	[MT_COMMENT] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[MT_KEY1] ASC,
	[MT_KEY2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BUCKETING_COLS]    Script Date: 11/24/2019 1:25:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BUCKETING_COLS](
	[SD_ID] [bigint] NOT NULL,
	[BUCKET_COL_NAME] [nvarchar](255) NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [BUCKETING_COLS_PK] PRIMARY KEY CLUSTERED 
(
	[SD_ID] ASC,
	[INTEGER_IDX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CDS]    Script Date: 11/24/2019 1:25:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CDS](
	[CD_ID] [bigint] NOT NULL,
 CONSTRAINT [CDS_PK] PRIMARY KEY CLUSTERED 
(
	[CD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COLUMNS_V2]    Script Date: 11/24/2019 1:25:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COLUMNS_V2](
	[CD_ID] [bigint] NOT NULL,
	[COMMENT] [nvarchar](256) NULL,
	[COLUMN_NAME] [nvarchar](767) NOT NULL,
	[TYPE_NAME] [varchar](max) NOT NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [COLUMNS_PK] PRIMARY KEY CLUSTERED 
(
	[CD_ID] ASC,
	[COLUMN_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMPACTION_QUEUE]    Script Date: 11/24/2019 1:25:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPACTION_QUEUE](
	[CQ_ID] [bigint] NOT NULL,
	[CQ_DATABASE] [nvarchar](128) NOT NULL,
	[CQ_TABLE] [nvarchar](128) NOT NULL,
	[CQ_PARTITION] [nvarchar](767) NULL,
	[CQ_STATE] [char](1) NOT NULL,
	[CQ_TYPE] [char](1) NOT NULL,
	[CQ_TBLPROPERTIES] [nvarchar](2048) NULL,
	[CQ_WORKER_ID] [nvarchar](128) NULL,
	[CQ_START] [bigint] NULL,
	[CQ_RUN_AS] [nvarchar](128) NULL,
	[CQ_HIGHEST_WRITE_ID] [bigint] NULL,
	[CQ_META_INFO] [varbinary](2048) NULL,
	[CQ_HADOOP_JOB_ID] [nvarchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[CQ_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMPLETED_COMPACTIONS]    Script Date: 11/24/2019 1:25:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPLETED_COMPACTIONS](
	[CC_ID] [bigint] NOT NULL,
	[CC_DATABASE] [nvarchar](128) NOT NULL,
	[CC_TABLE] [nvarchar](128) NOT NULL,
	[CC_PARTITION] [nvarchar](767) NULL,
	[CC_STATE] [char](1) NOT NULL,
	[CC_TYPE] [char](1) NOT NULL,
	[CC_TBLPROPERTIES] [nvarchar](2048) NULL,
	[CC_WORKER_ID] [nvarchar](128) NULL,
	[CC_START] [bigint] NULL,
	[CC_END] [bigint] NULL,
	[CC_RUN_AS] [nvarchar](128) NULL,
	[CC_HIGHEST_WRITE_ID] [bigint] NULL,
	[CC_META_INFO] [varbinary](2048) NULL,
	[CC_HADOOP_JOB_ID] [nvarchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[CC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMPLETED_TXN_COMPONENTS]    Script Date: 11/24/2019 1:25:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPLETED_TXN_COMPONENTS](
	[CTC_TXNID] [bigint] NOT NULL,
	[CTC_DATABASE] [nvarchar](128) NOT NULL,
	[CTC_TABLE] [nvarchar](128) NULL,
	[CTC_PARTITION] [nvarchar](767) NULL,
	[CTC_TIMESTAMP] [datetime2](7) NOT NULL,
	[CTC_WRITEID] [bigint] NULL,
	[CTC_UPDATE_DELETE] [char](1) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTLGS]    Script Date: 11/24/2019 1:25:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTLGS](
	[CTLG_ID] [bigint] NOT NULL,
	[NAME] [nvarchar](256) NULL,
	[DESC] [nvarchar](4000) NULL,
	[LOCATION_URI] [nvarchar](4000) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CTLG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DATABASE_PARAMS]    Script Date: 11/24/2019 1:25:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DATABASE_PARAMS](
	[DB_ID] [bigint] NOT NULL,
	[PARAM_KEY] [nvarchar](180) NOT NULL,
	[PARAM_VALUE] [nvarchar](4000) NULL,
 CONSTRAINT [DATABASE_PARAMS_PK] PRIMARY KEY CLUSTERED 
(
	[DB_ID] ASC,
	[PARAM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DB_PRIVS]    Script Date: 11/24/2019 1:25:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DB_PRIVS](
	[DB_GRANT_ID] [bigint] NOT NULL,
	[CREATE_TIME] [int] NOT NULL,
	[DB_ID] [bigint] NULL,
	[GRANT_OPTION] [smallint] NOT NULL,
	[GRANTOR] [nvarchar](128) NULL,
	[GRANTOR_TYPE] [nvarchar](128) NULL,
	[PRINCIPAL_NAME] [nvarchar](128) NULL,
	[PRINCIPAL_TYPE] [nvarchar](128) NULL,
	[DB_PRIV] [nvarchar](128) NULL,
	[AUTHORIZER] [nvarchar](128) NULL,
 CONSTRAINT [DB_PRIVS_PK] PRIMARY KEY CLUSTERED 
(
	[DB_GRANT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DBS]    Script Date: 11/24/2019 1:25:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DBS](
	[DB_ID] [bigint] NOT NULL,
	[DESC] [nvarchar](4000) NULL,
	[DB_LOCATION_URI] [nvarchar](4000) NOT NULL,
	[NAME] [nvarchar](128) NULL,
	[OWNER_NAME] [nvarchar](128) NULL,
	[OWNER_TYPE] [nvarchar](10) NULL,
	[CTLG_NAME] [nvarchar](256) NULL,
 CONSTRAINT [DBS_PK] PRIMARY KEY CLUSTERED 
(
	[DB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DELEGATION_TOKENS]    Script Date: 11/24/2019 1:25:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DELEGATION_TOKENS](
	[TOKEN_IDENT] [nvarchar](767) NOT NULL,
	[TOKEN] [nvarchar](767) NULL,
 CONSTRAINT [DELEGATION_TOKENS_PK] PRIMARY KEY CLUSTERED 
(
	[TOKEN_IDENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FUNC_RU]    Script Date: 11/24/2019 1:25:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FUNC_RU](
	[FUNC_ID] [bigint] NOT NULL,
	[RESOURCE_TYPE] [int] NOT NULL,
	[RESOURCE_URI] [nvarchar](4000) NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [FUNC_RU_PK] PRIMARY KEY CLUSTERED 
(
	[FUNC_ID] ASC,
	[INTEGER_IDX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FUNCS]    Script Date: 11/24/2019 1:25:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FUNCS](
	[FUNC_ID] [bigint] NOT NULL,
	[CLASS_NAME] [nvarchar](4000) NULL,
	[CREATE_TIME] [int] NOT NULL,
	[DB_ID] [bigint] NULL,
	[FUNC_NAME] [nvarchar](128) NULL,
	[FUNC_TYPE] [int] NOT NULL,
	[OWNER_NAME] [nvarchar](128) NULL,
	[OWNER_TYPE] [nvarchar](10) NULL,
 CONSTRAINT [FUNCS_PK] PRIMARY KEY CLUSTERED 
(
	[FUNC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GLOBAL_PRIVS]    Script Date: 11/24/2019 1:25:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GLOBAL_PRIVS](
	[USER_GRANT_ID] [bigint] NOT NULL,
	[CREATE_TIME] [int] NOT NULL,
	[GRANT_OPTION] [smallint] NOT NULL,
	[GRANTOR] [nvarchar](128) NULL,
	[GRANTOR_TYPE] [nvarchar](128) NULL,
	[PRINCIPAL_NAME] [nvarchar](128) NULL,
	[PRINCIPAL_TYPE] [nvarchar](128) NULL,
	[USER_PRIV] [nvarchar](128) NULL,
	[AUTHORIZER] [nvarchar](128) NULL,
 CONSTRAINT [GLOBAL_PRIVS_PK] PRIMARY KEY CLUSTERED 
(
	[USER_GRANT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HIVE_LOCKS]    Script Date: 11/24/2019 1:25:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HIVE_LOCKS](
	[HL_LOCK_EXT_ID] [bigint] NOT NULL,
	[HL_LOCK_INT_ID] [bigint] NOT NULL,
	[HL_TXNID] [bigint] NOT NULL,
	[HL_DB] [nvarchar](128) NOT NULL,
	[HL_TABLE] [nvarchar](128) NULL,
	[HL_PARTITION] [nvarchar](767) NULL,
	[HL_LOCK_STATE] [char](1) NOT NULL,
	[HL_LOCK_TYPE] [char](1) NOT NULL,
	[HL_LAST_HEARTBEAT] [bigint] NOT NULL,
	[HL_ACQUIRED_AT] [bigint] NULL,
	[HL_USER] [nvarchar](128) NOT NULL,
	[HL_HOST] [nvarchar](128) NOT NULL,
	[HL_HEARTBEAT_COUNT] [int] NULL,
	[HL_AGENT_INFO] [nvarchar](128) NULL,
	[HL_BLOCKEDBY_EXT_ID] [bigint] NULL,
	[HL_BLOCKEDBY_INT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[HL_LOCK_EXT_ID] ASC,
	[HL_LOCK_INT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[I_SCHEMA]    Script Date: 11/24/2019 1:25:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[I_SCHEMA](
	[SCHEMA_ID] [bigint] NOT NULL,
	[SCHEMA_TYPE] [int] NOT NULL,
	[NAME] [nvarchar](256) NULL,
	[DB_ID] [bigint] NULL,
	[COMPATIBILITY] [int] NOT NULL,
	[VALIDATION_LEVEL] [int] NOT NULL,
	[CAN_EVOLVE] [bit] NOT NULL,
	[SCHEMA_GROUP] [nvarchar](256) NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
PRIMARY KEY CLUSTERED 
(
	[SCHEMA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IDXS]    Script Date: 11/24/2019 1:25:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IDXS](
	[INDEX_ID] [bigint] NOT NULL,
	[CREATE_TIME] [int] NOT NULL,
	[DEFERRED_REBUILD] [bit] NOT NULL,
	[INDEX_HANDLER_CLASS] [nvarchar](4000) NULL,
	[INDEX_NAME] [nvarchar](128) NULL,
	[INDEX_TBL_ID] [bigint] NULL,
	[LAST_ACCESS_TIME] [int] NOT NULL,
	[ORIG_TBL_ID] [bigint] NULL,
	[SD_ID] [bigint] NULL,
 CONSTRAINT [IDXS_PK] PRIMARY KEY CLUSTERED 
(
	[INDEX_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INDEX_PARAMS]    Script Date: 11/24/2019 1:25:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INDEX_PARAMS](
	[INDEX_ID] [bigint] NOT NULL,
	[PARAM_KEY] [nvarchar](256) NOT NULL,
	[PARAM_VALUE] [nvarchar](4000) NULL,
 CONSTRAINT [INDEX_PARAMS_PK] PRIMARY KEY CLUSTERED 
(
	[INDEX_ID] ASC,
	[PARAM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KEY_CONSTRAINTS]    Script Date: 11/24/2019 1:25:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KEY_CONSTRAINTS](
	[CHILD_CD_ID] [bigint] NULL,
	[CHILD_INTEGER_IDX] [int] NULL,
	[CHILD_TBL_ID] [bigint] NULL,
	[PARENT_CD_ID] [bigint] NULL,
	[PARENT_INTEGER_IDX] [int] NOT NULL,
	[PARENT_TBL_ID] [bigint] NOT NULL,
	[POSITION] [int] NOT NULL,
	[CONSTRAINT_NAME] [varchar](400) NOT NULL,
	[CONSTRAINT_TYPE] [smallint] NOT NULL,
	[UPDATE_RULE] [smallint] NULL,
	[DELETE_RULE] [smallint] NULL,
	[ENABLE_VALIDATE_RELY] [smallint] NOT NULL,
	[DEFAULT_VALUE] [varchar](400) NULL,
 CONSTRAINT [CONSTRAINTS_PK] PRIMARY KEY CLUSTERED 
(
	[CONSTRAINT_NAME] ASC,
	[POSITION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MASTER_KEYS]    Script Date: 11/24/2019 1:25:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MASTER_KEYS](
	[KEY_ID] [int] NOT NULL,
	[MASTER_KEY] [nvarchar](767) NULL,
 CONSTRAINT [MASTER_KEYS_PK] PRIMARY KEY CLUSTERED 
(
	[KEY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MATERIALIZATION_REBUILD_LOCKS]    Script Date: 11/24/2019 1:25:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MATERIALIZATION_REBUILD_LOCKS](
	[MRL_TXN_ID] [bigint] NOT NULL,
	[MRL_DB_NAME] [nvarchar](128) NOT NULL,
	[MRL_TBL_NAME] [nvarchar](256) NOT NULL,
	[MRL_LAST_HEARTBEAT] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MRL_TXN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[METASTORE_DB_PROPERTIES]    Script Date: 11/24/2019 1:25:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[METASTORE_DB_PROPERTIES](
	[PROPERTY_KEY] [varchar](255) NOT NULL,
	[PROPERTY_VALUE] [varchar](1000) NOT NULL,
	[DESCRIPTION] [varchar](1000) NULL,
 CONSTRAINT [PROPERTY_KEY_PK] PRIMARY KEY CLUSTERED 
(
	[PROPERTY_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MIN_HISTORY_LEVEL]    Script Date: 11/24/2019 1:25:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MIN_HISTORY_LEVEL](
	[MHL_TXNID] [bigint] NOT NULL,
	[MHL_MIN_OPEN_TXNID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MHL_TXNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MV_CREATION_METADATA]    Script Date: 11/24/2019 1:25:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MV_CREATION_METADATA](
	[MV_CREATION_METADATA_ID] [bigint] NOT NULL,
	[CAT_NAME] [nvarchar](256) NOT NULL,
	[DB_NAME] [nvarchar](128) NOT NULL,
	[TBL_NAME] [nvarchar](256) NOT NULL,
	[TXN_LIST] [text] NULL,
	[MATERIALIZATION_TIME] [bigint] NOT NULL,
 CONSTRAINT [MV_CREATION_METADATA_PK] PRIMARY KEY CLUSTERED 
(
	[MV_CREATION_METADATA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MV_TABLES_USED]    Script Date: 11/24/2019 1:25:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MV_TABLES_USED](
	[MV_CREATION_METADATA_ID] [bigint] NOT NULL,
	[TBL_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NEXT_COMPACTION_QUEUE_ID]    Script Date: 11/24/2019 1:25:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NEXT_COMPACTION_QUEUE_ID](
	[NCQ_NEXT] [bigint] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NEXT_LOCK_ID]    Script Date: 11/24/2019 1:25:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NEXT_LOCK_ID](
	[NL_NEXT] [bigint] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NEXT_TXN_ID]    Script Date: 11/24/2019 1:25:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NEXT_TXN_ID](
	[NTXN_NEXT] [bigint] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NEXT_WRITE_ID]    Script Date: 11/24/2019 1:25:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NEXT_WRITE_ID](
	[NWI_DATABASE] [nvarchar](128) NOT NULL,
	[NWI_TABLE] [nvarchar](256) NOT NULL,
	[NWI_NEXT] [bigint] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATION_LOG]    Script Date: 11/24/2019 1:25:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION_LOG](
	[NL_ID] [bigint] NOT NULL,
	[EVENT_ID] [bigint] NOT NULL,
	[EVENT_TIME] [int] NOT NULL,
	[EVENT_TYPE] [nvarchar](32) NOT NULL,
	[CAT_NAME] [nvarchar](128) NULL,
	[DB_NAME] [nvarchar](128) NULL,
	[TBL_NAME] [nvarchar](256) NULL,
	[MESSAGE_FORMAT] [nvarchar](16) NULL,
	[MESSAGE] [text] NULL,
 CONSTRAINT [NOTIFICATION_LOG_PK] PRIMARY KEY CLUSTERED 
(
	[NL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATION_SEQUENCE]    Script Date: 11/24/2019 1:25:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION_SEQUENCE](
	[NNI_ID] [bigint] NOT NULL,
	[NEXT_EVENT_ID] [bigint] NOT NULL,
 CONSTRAINT [NOTIFICATION_SEQUENCE_PK] PRIMARY KEY CLUSTERED 
(
	[NNI_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PART_COL_PRIVS]    Script Date: 11/24/2019 1:25:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PART_COL_PRIVS](
	[PART_COLUMN_GRANT_ID] [bigint] NOT NULL,
	[COLUMN_NAME] [nvarchar](767) NULL,
	[CREATE_TIME] [int] NOT NULL,
	[GRANT_OPTION] [smallint] NOT NULL,
	[GRANTOR] [nvarchar](128) NULL,
	[GRANTOR_TYPE] [nvarchar](128) NULL,
	[PART_ID] [bigint] NULL,
	[PRINCIPAL_NAME] [nvarchar](128) NULL,
	[PRINCIPAL_TYPE] [nvarchar](128) NULL,
	[PART_COL_PRIV] [nvarchar](128) NULL,
	[AUTHORIZER] [nvarchar](128) NULL,
 CONSTRAINT [PART_COL_PRIVS_PK] PRIMARY KEY CLUSTERED 
(
	[PART_COLUMN_GRANT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PART_COL_STATS]    Script Date: 11/24/2019 1:25:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PART_COL_STATS](
	[CS_ID] [bigint] NOT NULL,
	[AVG_COL_LEN] [float] NULL,
	[COLUMN_NAME] [nvarchar](767) NOT NULL,
	[COLUMN_TYPE] [nvarchar](128) NOT NULL,
	[DB_NAME] [nvarchar](128) NOT NULL,
	[BIG_DECIMAL_HIGH_VALUE] [nvarchar](255) NULL,
	[BIG_DECIMAL_LOW_VALUE] [nvarchar](255) NULL,
	[DOUBLE_HIGH_VALUE] [float] NULL,
	[DOUBLE_LOW_VALUE] [float] NULL,
	[LAST_ANALYZED] [bigint] NOT NULL,
	[LONG_HIGH_VALUE] [bigint] NULL,
	[LONG_LOW_VALUE] [bigint] NULL,
	[MAX_COL_LEN] [bigint] NULL,
	[NUM_DISTINCTS] [bigint] NULL,
	[BIT_VECTOR] [varbinary](max) NULL,
	[NUM_FALSES] [bigint] NULL,
	[NUM_NULLS] [bigint] NOT NULL,
	[NUM_TRUES] [bigint] NULL,
	[PART_ID] [bigint] NULL,
	[PARTITION_NAME] [nvarchar](767) NOT NULL,
	[TABLE_NAME] [nvarchar](256) NOT NULL,
	[CAT_NAME] [nvarchar](256) NOT NULL,
 CONSTRAINT [PART_COL_STATS_PK] PRIMARY KEY CLUSTERED 
(
	[CS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PART_PRIVS]    Script Date: 11/24/2019 1:25:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PART_PRIVS](
	[PART_GRANT_ID] [bigint] NOT NULL,
	[CREATE_TIME] [int] NOT NULL,
	[GRANT_OPTION] [smallint] NOT NULL,
	[GRANTOR] [nvarchar](128) NULL,
	[GRANTOR_TYPE] [nvarchar](128) NULL,
	[PART_ID] [bigint] NULL,
	[PRINCIPAL_NAME] [nvarchar](128) NULL,
	[PRINCIPAL_TYPE] [nvarchar](128) NULL,
	[PART_PRIV] [nvarchar](128) NULL,
	[AUTHORIZER] [nvarchar](128) NULL,
 CONSTRAINT [PART_PRIVS_PK] PRIMARY KEY CLUSTERED 
(
	[PART_GRANT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTITION_EVENTS]    Script Date: 11/24/2019 1:25:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTITION_EVENTS](
	[PART_NAME_ID] [bigint] NOT NULL,
	[CAT_NAME] [nvarchar](256) NULL,
	[DB_NAME] [nvarchar](128) NULL,
	[EVENT_TIME] [bigint] NOT NULL,
	[EVENT_TYPE] [int] NOT NULL,
	[PARTITION_NAME] [nvarchar](767) NULL,
	[TBL_NAME] [nvarchar](256) NULL,
 CONSTRAINT [PARTITION_EVENTS_PK] PRIMARY KEY CLUSTERED 
(
	[PART_NAME_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTITION_KEY_VALS]    Script Date: 11/24/2019 1:25:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTITION_KEY_VALS](
	[PART_ID] [bigint] NOT NULL,
	[PART_KEY_VAL] [nvarchar](255) NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [PARTITION_KEY_VALS_PK] PRIMARY KEY CLUSTERED 
(
	[PART_ID] ASC,
	[INTEGER_IDX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTITION_KEYS]    Script Date: 11/24/2019 1:25:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTITION_KEYS](
	[TBL_ID] [bigint] NOT NULL,
	[PKEY_COMMENT] [nvarchar](4000) NULL,
	[PKEY_NAME] [nvarchar](128) NOT NULL,
	[PKEY_TYPE] [nvarchar](767) NOT NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [PARTITION_KEY_PK] PRIMARY KEY CLUSTERED 
(
	[TBL_ID] ASC,
	[PKEY_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTITION_PARAMS]    Script Date: 11/24/2019 1:25:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTITION_PARAMS](
	[PART_ID] [bigint] NOT NULL,
	[PARAM_KEY] [nvarchar](256) NOT NULL,
	[PARAM_VALUE] [varchar](max) NULL,
 CONSTRAINT [PARTITION_PARAMS_PK] PRIMARY KEY CLUSTERED 
(
	[PART_ID] ASC,
	[PARAM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTITIONS]    Script Date: 11/24/2019 1:25:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTITIONS](
	[PART_ID] [bigint] NOT NULL,
	[CREATE_TIME] [int] NOT NULL,
	[LAST_ACCESS_TIME] [int] NOT NULL,
	[PART_NAME] [nvarchar](767) NULL,
	[SD_ID] [bigint] NULL,
	[TBL_ID] [bigint] NULL,
	[WRITE_ID] [bigint] NOT NULL,
 CONSTRAINT [PARTITIONS_PK] PRIMARY KEY CLUSTERED 
(
	[PART_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REPL_TXN_MAP]    Script Date: 11/24/2019 1:25:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPL_TXN_MAP](
	[RTM_REPL_POLICY] [nvarchar](256) NOT NULL,
	[RTM_SRC_TXN_ID] [bigint] NOT NULL,
	[RTM_TARGET_TXN_ID] [bigint] NOT NULL,
 CONSTRAINT [REPL_TXN_MAP_PK] PRIMARY KEY CLUSTERED 
(
	[RTM_REPL_POLICY] ASC,
	[RTM_SRC_TXN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLE_MAP]    Script Date: 11/24/2019 1:25:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLE_MAP](
	[ROLE_GRANT_ID] [bigint] NOT NULL,
	[ADD_TIME] [int] NOT NULL,
	[GRANT_OPTION] [smallint] NOT NULL,
	[GRANTOR] [nvarchar](128) NULL,
	[GRANTOR_TYPE] [nvarchar](128) NULL,
	[PRINCIPAL_NAME] [nvarchar](128) NULL,
	[PRINCIPAL_TYPE] [nvarchar](128) NULL,
	[ROLE_ID] [bigint] NULL,
 CONSTRAINT [ROLE_MAP_PK] PRIMARY KEY CLUSTERED 
(
	[ROLE_GRANT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLES]    Script Date: 11/24/2019 1:25:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLES](
	[ROLE_ID] [bigint] NOT NULL,
	[CREATE_TIME] [int] NOT NULL,
	[OWNER_NAME] [nvarchar](128) NULL,
	[ROLE_NAME] [nvarchar](128) NULL,
 CONSTRAINT [ROLES_PK] PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RUNTIME_STATS]    Script Date: 11/24/2019 1:25:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RUNTIME_STATS](
	[RS_ID] [bigint] NOT NULL,
	[CREATE_TIME] [bigint] NOT NULL,
	[WEIGHT] [bigint] NOT NULL,
	[PAYLOAD] [varbinary](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[RS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SCHEMA_VERSION]    Script Date: 11/24/2019 1:25:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCHEMA_VERSION](
	[SCHEMA_VERSION_ID] [bigint] NOT NULL,
	[SCHEMA_ID] [bigint] NULL,
	[VERSION] [int] NOT NULL,
	[CREATED_AT] [bigint] NOT NULL,
	[CD_ID] [bigint] NULL,
	[STATE] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[SCHEMA_TEXT] [varchar](max) NULL,
	[FINGERPRINT] [nvarchar](256) NULL,
	[SCHEMA_VERSION_NAME] [nvarchar](256) NULL,
	[SERDE_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[SCHEMA_VERSION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SCHEMA_ID] ASC,
	[VERSION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SD_PARAMS]    Script Date: 11/24/2019 1:25:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SD_PARAMS](
	[SD_ID] [bigint] NOT NULL,
	[PARAM_KEY] [nvarchar](256) NOT NULL,
	[PARAM_VALUE] [varchar](max) NULL,
 CONSTRAINT [SD_PARAMS_PK] PRIMARY KEY CLUSTERED 
(
	[SD_ID] ASC,
	[PARAM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SDS]    Script Date: 11/24/2019 1:25:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SDS](
	[SD_ID] [bigint] NOT NULL,
	[CD_ID] [bigint] NULL,
	[INPUT_FORMAT] [nvarchar](4000) NULL,
	[IS_COMPRESSED] [bit] NOT NULL,
	[IS_STOREDASSUBDIRECTORIES] [bit] NOT NULL,
	[LOCATION] [nvarchar](4000) NULL,
	[NUM_BUCKETS] [int] NOT NULL,
	[OUTPUT_FORMAT] [nvarchar](4000) NULL,
	[SERDE_ID] [bigint] NULL,
 CONSTRAINT [SDS_PK] PRIMARY KEY CLUSTERED 
(
	[SD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SEQUENCE_TABLE]    Script Date: 11/24/2019 1:25:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEQUENCE_TABLE](
	[SEQUENCE_NAME] [nvarchar](256) NOT NULL,
	[NEXT_VAL] [bigint] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SERDE_PARAMS]    Script Date: 11/24/2019 1:25:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SERDE_PARAMS](
	[SERDE_ID] [bigint] NOT NULL,
	[PARAM_KEY] [nvarchar](256) NOT NULL,
	[PARAM_VALUE] [varchar](max) NULL,
 CONSTRAINT [SERDE_PARAMS_PK] PRIMARY KEY CLUSTERED 
(
	[SERDE_ID] ASC,
	[PARAM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SERDES]    Script Date: 11/24/2019 1:25:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SERDES](
	[SERDE_ID] [bigint] NOT NULL,
	[NAME] [nvarchar](128) NULL,
	[SLIB] [nvarchar](4000) NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[SERIALIZER_CLASS] [nvarchar](4000) NULL,
	[DESERIALIZER_CLASS] [nvarchar](4000) NULL,
	[SERDE_TYPE] [int] NULL,
 CONSTRAINT [SERDES_PK] PRIMARY KEY CLUSTERED 
(
	[SERDE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SKEWED_COL_NAMES]    Script Date: 11/24/2019 1:25:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SKEWED_COL_NAMES](
	[SD_ID] [bigint] NOT NULL,
	[SKEWED_COL_NAME] [nvarchar](255) NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [SKEWED_COL_NAMES_PK] PRIMARY KEY CLUSTERED 
(
	[SD_ID] ASC,
	[INTEGER_IDX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SKEWED_COL_VALUE_LOC_MAP]    Script Date: 11/24/2019 1:25:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SKEWED_COL_VALUE_LOC_MAP](
	[SD_ID] [bigint] NOT NULL,
	[STRING_LIST_ID_KID] [bigint] NOT NULL,
	[LOCATION] [nvarchar](4000) NULL,
 CONSTRAINT [SKEWED_COL_VALUE_LOC_MAP_PK] PRIMARY KEY CLUSTERED 
(
	[SD_ID] ASC,
	[STRING_LIST_ID_KID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SKEWED_STRING_LIST]    Script Date: 11/24/2019 1:25:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SKEWED_STRING_LIST](
	[STRING_LIST_ID] [bigint] NOT NULL,
 CONSTRAINT [SKEWED_STRING_LIST_PK] PRIMARY KEY CLUSTERED 
(
	[STRING_LIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SKEWED_STRING_LIST_VALUES]    Script Date: 11/24/2019 1:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SKEWED_STRING_LIST_VALUES](
	[STRING_LIST_ID] [bigint] NOT NULL,
	[STRING_LIST_VALUE] [nvarchar](255) NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [SKEWED_STRING_LIST_VALUES_PK] PRIMARY KEY CLUSTERED 
(
	[STRING_LIST_ID] ASC,
	[INTEGER_IDX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SKEWED_VALUES]    Script Date: 11/24/2019 1:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SKEWED_VALUES](
	[SD_ID_OID] [bigint] NOT NULL,
	[STRING_LIST_ID_EID] [bigint] NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [SKEWED_VALUES_PK] PRIMARY KEY CLUSTERED 
(
	[SD_ID_OID] ASC,
	[INTEGER_IDX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SORT_COLS]    Script Date: 11/24/2019 1:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SORT_COLS](
	[SD_ID] [bigint] NOT NULL,
	[COLUMN_NAME] [nvarchar](767) NULL,
	[ORDER] [int] NOT NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [SORT_COLS_PK] PRIMARY KEY CLUSTERED 
(
	[SD_ID] ASC,
	[INTEGER_IDX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAB_COL_STATS]    Script Date: 11/24/2019 1:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_COL_STATS](
	[CS_ID] [bigint] NOT NULL,
	[AVG_COL_LEN] [float] NULL,
	[COLUMN_NAME] [nvarchar](767) NOT NULL,
	[COLUMN_TYPE] [nvarchar](128) NOT NULL,
	[DB_NAME] [nvarchar](128) NOT NULL,
	[BIG_DECIMAL_HIGH_VALUE] [nvarchar](255) NULL,
	[BIG_DECIMAL_LOW_VALUE] [nvarchar](255) NULL,
	[DOUBLE_HIGH_VALUE] [float] NULL,
	[DOUBLE_LOW_VALUE] [float] NULL,
	[LAST_ANALYZED] [bigint] NOT NULL,
	[LONG_HIGH_VALUE] [bigint] NULL,
	[LONG_LOW_VALUE] [bigint] NULL,
	[MAX_COL_LEN] [bigint] NULL,
	[NUM_DISTINCTS] [bigint] NULL,
	[BIT_VECTOR] [varbinary](max) NULL,
	[NUM_FALSES] [bigint] NULL,
	[NUM_NULLS] [bigint] NOT NULL,
	[NUM_TRUES] [bigint] NULL,
	[TBL_ID] [bigint] NULL,
	[TABLE_NAME] [nvarchar](256) NOT NULL,
	[CAT_NAME] [nvarchar](256) NOT NULL,
 CONSTRAINT [TAB_COL_STATS_PK] PRIMARY KEY CLUSTERED 
(
	[CS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABLE_PARAMS]    Script Date: 11/24/2019 1:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABLE_PARAMS](
	[TBL_ID] [bigint] NOT NULL,
	[PARAM_KEY] [nvarchar](256) NOT NULL,
	[PARAM_VALUE] [varchar](max) NULL,
 CONSTRAINT [TABLE_PARAMS_PK] PRIMARY KEY CLUSTERED 
(
	[TBL_ID] ASC,
	[PARAM_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_COL_PRIVS]    Script Date: 11/24/2019 1:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_COL_PRIVS](
	[TBL_COLUMN_GRANT_ID] [bigint] NOT NULL,
	[COLUMN_NAME] [nvarchar](767) NULL,
	[CREATE_TIME] [int] NOT NULL,
	[GRANT_OPTION] [smallint] NOT NULL,
	[GRANTOR] [nvarchar](128) NULL,
	[GRANTOR_TYPE] [nvarchar](128) NULL,
	[PRINCIPAL_NAME] [nvarchar](128) NULL,
	[PRINCIPAL_TYPE] [nvarchar](128) NULL,
	[TBL_COL_PRIV] [nvarchar](128) NULL,
	[TBL_ID] [bigint] NULL,
	[AUTHORIZER] [nvarchar](128) NULL,
 CONSTRAINT [TBL_COL_PRIVS_PK] PRIMARY KEY CLUSTERED 
(
	[TBL_COLUMN_GRANT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_PRIVS]    Script Date: 11/24/2019 1:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_PRIVS](
	[TBL_GRANT_ID] [bigint] NOT NULL,
	[CREATE_TIME] [int] NOT NULL,
	[GRANT_OPTION] [smallint] NOT NULL,
	[GRANTOR] [nvarchar](128) NULL,
	[GRANTOR_TYPE] [nvarchar](128) NULL,
	[PRINCIPAL_NAME] [nvarchar](128) NULL,
	[PRINCIPAL_TYPE] [nvarchar](128) NULL,
	[TBL_PRIV] [nvarchar](128) NULL,
	[TBL_ID] [bigint] NULL,
	[AUTHORIZER] [nvarchar](128) NULL,
 CONSTRAINT [TBL_PRIVS_PK] PRIMARY KEY CLUSTERED 
(
	[TBL_GRANT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBLS]    Script Date: 11/24/2019 1:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLS](
	[TBL_ID] [bigint] NOT NULL,
	[CREATE_TIME] [int] NOT NULL,
	[DB_ID] [bigint] NULL,
	[LAST_ACCESS_TIME] [int] NOT NULL,
	[OWNER] [nvarchar](767) NULL,
	[OWNER_TYPE] [nvarchar](10) NULL,
	[RETENTION] [int] NOT NULL,
	[SD_ID] [bigint] NULL,
	[TBL_NAME] [nvarchar](256) NULL,
	[TBL_TYPE] [nvarchar](128) NULL,
	[VIEW_EXPANDED_TEXT] [text] NULL,
	[VIEW_ORIGINAL_TEXT] [text] NULL,
	[IS_REWRITE_ENABLED] [bit] NOT NULL,
	[WRITE_ID] [bigint] NOT NULL,
 CONSTRAINT [TBLS_PK] PRIMARY KEY CLUSTERED 
(
	[TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TXN_COMPONENTS]    Script Date: 11/24/2019 1:25:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TXN_COMPONENTS](
	[TC_TXNID] [bigint] NOT NULL,
	[TC_DATABASE] [nvarchar](128) NOT NULL,
	[TC_TABLE] [nvarchar](128) NULL,
	[TC_PARTITION] [nvarchar](767) NULL,
	[TC_OPERATION_TYPE] [char](1) NOT NULL,
	[TC_WRITEID] [bigint] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TXN_TO_WRITE_ID]    Script Date: 11/24/2019 1:25:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TXN_TO_WRITE_ID](
	[T2W_TXNID] [bigint] NOT NULL,
	[T2W_DATABASE] [nvarchar](128) NOT NULL,
	[T2W_TABLE] [nvarchar](256) NOT NULL,
	[T2W_WRITEID] [bigint] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TXN_WRITE_NOTIFICATION_LOG]    Script Date: 11/24/2019 1:25:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TXN_WRITE_NOTIFICATION_LOG](
	[WNL_ID] [bigint] NOT NULL,
	[WNL_TXNID] [bigint] NOT NULL,
	[WNL_WRITEID] [bigint] NOT NULL,
	[WNL_DATABASE] [nvarchar](128) NOT NULL,
	[WNL_TABLE] [nvarchar](128) NOT NULL,
	[WNL_PARTITION] [nvarchar](767) NOT NULL,
	[WNL_TABLE_OBJ] [text] NOT NULL,
	[WNL_PARTITION_OBJ] [text] NULL,
	[WNL_FILES] [text] NULL,
	[WNL_EVENT_TIME] [int] NOT NULL,
 CONSTRAINT [TXN_WRITE_NOTIFICATION_LOG_PK] PRIMARY KEY CLUSTERED 
(
	[WNL_TXNID] ASC,
	[WNL_DATABASE] ASC,
	[WNL_TABLE] ASC,
	[WNL_PARTITION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TXNS]    Script Date: 11/24/2019 1:25:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TXNS](
	[TXN_ID] [bigint] NOT NULL,
	[TXN_STATE] [char](1) NOT NULL,
	[TXN_STARTED] [bigint] NOT NULL,
	[TXN_LAST_HEARTBEAT] [bigint] NOT NULL,
	[TXN_USER] [nvarchar](128) NOT NULL,
	[TXN_HOST] [nvarchar](128) NOT NULL,
	[TXN_AGENT_INFO] [nvarchar](128) NULL,
	[TXN_META_INFO] [nvarchar](128) NULL,
	[TXN_HEARTBEAT_COUNT] [int] NULL,
	[TXN_TYPE] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[TXN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TYPE_FIELDS]    Script Date: 11/24/2019 1:25:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TYPE_FIELDS](
	[TYPE_NAME] [bigint] NOT NULL,
	[COMMENT] [nvarchar](256) NULL,
	[FIELD_NAME] [nvarchar](128) NOT NULL,
	[FIELD_TYPE] [nvarchar](767) NOT NULL,
	[INTEGER_IDX] [int] NOT NULL,
 CONSTRAINT [TYPE_FIELDS_PK] PRIMARY KEY CLUSTERED 
(
	[TYPE_NAME] ASC,
	[FIELD_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TYPES]    Script Date: 11/24/2019 1:25:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TYPES](
	[TYPES_ID] [bigint] NOT NULL,
	[TYPE_NAME] [nvarchar](128) NULL,
	[TYPE1] [nvarchar](767) NULL,
	[TYPE2] [nvarchar](767) NULL,
 CONSTRAINT [TYPES_PK] PRIMARY KEY CLUSTERED 
(
	[TYPES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VERSION]    Script Date: 11/24/2019 1:25:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VERSION](
	[VER_ID] [bigint] NOT NULL,
	[SCHEMA_VERSION] [nvarchar](127) NOT NULL,
	[VERSION_COMMENT] [nvarchar](255) NOT NULL,
 CONSTRAINT [VERSION_PK] PRIMARY KEY CLUSTERED 
(
	[VER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WM_MAPPING]    Script Date: 11/24/2019 1:25:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WM_MAPPING](
	[MAPPING_ID] [bigint] NOT NULL,
	[RP_ID] [bigint] NOT NULL,
	[ENTITY_TYPE] [nvarchar](128) NOT NULL,
	[ENTITY_NAME] [nvarchar](128) NOT NULL,
	[POOL_ID] [bigint] NULL,
	[ORDERING] [int] NULL,
 CONSTRAINT [WM_MAPPING_PK] PRIMARY KEY CLUSTERED 
(
	[MAPPING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WM_POOL]    Script Date: 11/24/2019 1:25:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WM_POOL](
	[POOL_ID] [bigint] NOT NULL,
	[RP_ID] [bigint] NOT NULL,
	[PATH] [nvarchar](1024) NOT NULL,
	[ALLOC_FRACTION] [float] NULL,
	[QUERY_PARALLELISM] [int] NULL,
	[SCHEDULING_POLICY] [nvarchar](1024) NULL,
 CONSTRAINT [WM_POOL_PK] PRIMARY KEY CLUSTERED 
(
	[POOL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WM_POOL_TO_TRIGGER]    Script Date: 11/24/2019 1:25:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WM_POOL_TO_TRIGGER](
	[POOL_ID] [bigint] NOT NULL,
	[TRIGGER_ID] [bigint] NOT NULL,
 CONSTRAINT [WM_POOL_TO_TRIGGER_PK] PRIMARY KEY CLUSTERED 
(
	[POOL_ID] ASC,
	[TRIGGER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WM_RESOURCEPLAN]    Script Date: 11/24/2019 1:25:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WM_RESOURCEPLAN](
	[RP_ID] [bigint] NOT NULL,
	[NAME] [nvarchar](128) NOT NULL,
	[QUERY_PARALLELISM] [int] NULL,
	[STATUS] [nvarchar](20) NOT NULL,
	[DEFAULT_POOL_ID] [bigint] NULL,
 CONSTRAINT [WM_RESOURCEPLAN_PK] PRIMARY KEY CLUSTERED 
(
	[RP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WM_TRIGGER]    Script Date: 11/24/2019 1:25:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WM_TRIGGER](
	[TRIGGER_ID] [bigint] NOT NULL,
	[RP_ID] [bigint] NOT NULL,
	[NAME] [nvarchar](128) NOT NULL,
	[TRIGGER_EXPRESSION] [nvarchar](1024) NULL,
	[ACTION_EXPRESSION] [nvarchar](1024) NULL,
	[IS_IN_UNMANAGED] [bit] NOT NULL,
 CONSTRAINT [WM_TRIGGER_PK] PRIMARY KEY CLUSTERED 
(
	[TRIGGER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WRITE_SET]    Script Date: 11/24/2019 1:25:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WRITE_SET](
	[WS_DATABASE] [nvarchar](128) NOT NULL,
	[WS_TABLE] [nvarchar](128) NOT NULL,
	[WS_PARTITION] [nvarchar](767) NULL,
	[WS_TXNID] [bigint] NOT NULL,
	[WS_COMMIT_ID] [bigint] NOT NULL,
	[WS_OPERATION_TYPE] [char](1) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Index [BUCKETING_COLS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [BUCKETING_COLS_N49] ON [dbo].[BUCKETING_COLS]
(
	[SD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [COLUMNS_V2_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [COLUMNS_V2_N49] ON [dbo].[COLUMNS_V2]
(
	[CD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [COMPLETED_TXN_COMPONENTS_IDX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [COMPLETED_TXN_COMPONENTS_IDX] ON [dbo].[COMPLETED_TXN_COMPONENTS]
(
	[CTC_DATABASE] ASC,
	[CTC_TABLE] ASC,
	[CTC_PARTITION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUE_CTLG]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUE_CTLG] ON [dbo].[CTLGS]
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [DATABASE_PARAMS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [DATABASE_PARAMS_N49] ON [dbo].[DATABASE_PARAMS]
(
	[DB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [DB_PRIVS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [DB_PRIVS_N49] ON [dbo].[DB_PRIVS]
(
	[DB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [DBPRIVILEGEINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [DBPRIVILEGEINDEX] ON [dbo].[DB_PRIVS]
(
	[AUTHORIZER] ASC,
	[DB_ID] ASC,
	[PRINCIPAL_NAME] ASC,
	[PRINCIPAL_TYPE] ASC,
	[DB_PRIV] ASC,
	[GRANTOR] ASC,
	[GRANTOR_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUE_DATABASE]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUE_DATABASE] ON [dbo].[DBS]
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUEDATABASE]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUEDATABASE] ON [dbo].[DBS]
(
	[NAME] ASC,
	[CTLG_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [FUNC_RU_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [FUNC_RU_N49] ON [dbo].[FUNC_RU]
(
	[FUNC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [FUNCS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [FUNCS_N49] ON [dbo].[FUNCS]
(
	[DB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUEFUNCTION]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUEFUNCTION] ON [dbo].[FUNCS]
(
	[FUNC_NAME] ASC,
	[DB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [GLOBALPRIVILEGEINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [GLOBALPRIVILEGEINDEX] ON [dbo].[GLOBAL_PRIVS]
(
	[AUTHORIZER] ASC,
	[PRINCIPAL_NAME] ASC,
	[PRINCIPAL_TYPE] ASC,
	[USER_PRIV] ASC,
	[GRANTOR] ASC,
	[GRANTOR_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDXS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [IDXS_N49] ON [dbo].[IDXS]
(
	[INDEX_TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDXS_N50]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [IDXS_N50] ON [dbo].[IDXS]
(
	[ORIG_TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDXS_N51]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [IDXS_N51] ON [dbo].[IDXS]
(
	[SD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUEINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUEINDEX] ON [dbo].[IDXS]
(
	[INDEX_NAME] ASC,
	[ORIG_TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX_PARAMS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [INDEX_PARAMS_N49] ON [dbo].[INDEX_PARAMS]
(
	[INDEX_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [CONSTRAINTS_CONSTRAINT_TYPE_INDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [CONSTRAINTS_CONSTRAINT_TYPE_INDEX] ON [dbo].[KEY_CONSTRAINTS]
(
	[CONSTRAINT_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [CONSTRAINTS_PARENT_TBL_ID__INDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [CONSTRAINTS_PARENT_TBL_ID__INDEX] ON [dbo].[KEY_CONSTRAINTS]
(
	[PARENT_TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [KEY_CONSTRAINTS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [KEY_CONSTRAINTS_N49] ON [dbo].[KEY_CONSTRAINTS]
(
	[CHILD_TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [KEY_CONSTRAINTS_N50]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [KEY_CONSTRAINTS_N50] ON [dbo].[KEY_CONSTRAINTS]
(
	[CHILD_CD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [KEY_CONSTRAINTS_N51]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [KEY_CONSTRAINTS_N51] ON [dbo].[KEY_CONSTRAINTS]
(
	[PARENT_CD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [MIN_HISTORY_LEVEL_IDX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [MIN_HISTORY_LEVEL_IDX] ON [dbo].[MIN_HISTORY_LEVEL]
(
	[MHL_MIN_OPEN_TXNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [MV_UNIQUE_TABLE]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [MV_UNIQUE_TABLE] ON [dbo].[MV_CREATION_METADATA]
(
	[TBL_NAME] ASC,
	[DB_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [NEXT_WRITE_ID_IDX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [NEXT_WRITE_ID_IDX] ON [dbo].[NEXT_WRITE_ID]
(
	[NWI_DATABASE] ASC,
	[NWI_TABLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PART_COL_PRIVS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PART_COL_PRIVS_N49] ON [dbo].[PART_COL_PRIVS]
(
	[PART_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [PARTITIONCOLUMNPRIVILEGEINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PARTITIONCOLUMNPRIVILEGEINDEX] ON [dbo].[PART_COL_PRIVS]
(
	[AUTHORIZER] ASC,
	[PART_ID] ASC,
	[COLUMN_NAME] ASC,
	[PRINCIPAL_NAME] ASC,
	[PRINCIPAL_TYPE] ASC,
	[PART_COL_PRIV] ASC,
	[GRANTOR] ASC,
	[GRANTOR_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PART_COL_STATS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PART_COL_STATS_N49] ON [dbo].[PART_COL_STATS]
(
	[PART_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [PCS_STATS_IDX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PCS_STATS_IDX] ON [dbo].[PART_COL_STATS]
(
	[CAT_NAME] ASC,
	[DB_NAME] ASC,
	[TABLE_NAME] ASC,
	[COLUMN_NAME] ASC,
	[PARTITION_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PART_PRIVS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PART_PRIVS_N49] ON [dbo].[PART_PRIVS]
(
	[PART_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [PARTPRIVILEGEINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PARTPRIVILEGEINDEX] ON [dbo].[PART_PRIVS]
(
	[AUTHORIZER] ASC,
	[PART_ID] ASC,
	[PRINCIPAL_NAME] ASC,
	[PRINCIPAL_TYPE] ASC,
	[PART_PRIV] ASC,
	[GRANTOR] ASC,
	[GRANTOR_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [PARTITIONEVENTINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PARTITIONEVENTINDEX] ON [dbo].[PARTITION_EVENTS]
(
	[PARTITION_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PARTITION_KEY_VALS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PARTITION_KEY_VALS_N49] ON [dbo].[PARTITION_KEY_VALS]
(
	[PART_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PARTITION_KEYS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PARTITION_KEYS_N49] ON [dbo].[PARTITION_KEYS]
(
	[TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PARTITION_PARAMS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PARTITION_PARAMS_N49] ON [dbo].[PARTITION_PARAMS]
(
	[PART_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PARTITIONS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PARTITIONS_N49] ON [dbo].[PARTITIONS]
(
	[SD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PARTITIONS_N50]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [PARTITIONS_N50] ON [dbo].[PARTITIONS]
(
	[TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUEPARTITION]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUEPARTITION] ON [dbo].[PARTITIONS]
(
	[PART_NAME] ASC,
	[TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [ROLE_MAP_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [ROLE_MAP_N49] ON [dbo].[ROLE_MAP]
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [USERROLEMAPINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [USERROLEMAPINDEX] ON [dbo].[ROLE_MAP]
(
	[PRINCIPAL_NAME] ASC,
	[ROLE_ID] ASC,
	[GRANTOR] ASC,
	[GRANTOR_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [ROLEENTITYINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [ROLEENTITYINDEX] ON [dbo].[ROLES]
(
	[ROLE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_RUNTIME_STATS_CREATE_TIME]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [IDX_RUNTIME_STATS_CREATE_TIME] ON [dbo].[RUNTIME_STATS]
(
	[CREATE_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SD_PARAMS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SD_PARAMS_N49] ON [dbo].[SD_PARAMS]
(
	[SD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SDS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SDS_N49] ON [dbo].[SDS]
(
	[SERDE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SDS_N50]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SDS_N50] ON [dbo].[SDS]
(
	[CD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [PART_TABLE_PK]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [PART_TABLE_PK] ON [dbo].[SEQUENCE_TABLE]
(
	[SEQUENCE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SERDE_PARAMS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SERDE_PARAMS_N49] ON [dbo].[SERDE_PARAMS]
(
	[SERDE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SKEWED_COL_NAMES_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SKEWED_COL_NAMES_N49] ON [dbo].[SKEWED_COL_NAMES]
(
	[SD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SKEWED_COL_VALUE_LOC_MAP_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SKEWED_COL_VALUE_LOC_MAP_N49] ON [dbo].[SKEWED_COL_VALUE_LOC_MAP]
(
	[SD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SKEWED_COL_VALUE_LOC_MAP_N50]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SKEWED_COL_VALUE_LOC_MAP_N50] ON [dbo].[SKEWED_COL_VALUE_LOC_MAP]
(
	[STRING_LIST_ID_KID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SKEWED_STRING_LIST_VALUES_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SKEWED_STRING_LIST_VALUES_N49] ON [dbo].[SKEWED_STRING_LIST_VALUES]
(
	[STRING_LIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SKEWED_VALUES_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SKEWED_VALUES_N49] ON [dbo].[SKEWED_VALUES]
(
	[STRING_LIST_ID_EID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SKEWED_VALUES_N50]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SKEWED_VALUES_N50] ON [dbo].[SKEWED_VALUES]
(
	[SD_ID_OID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [SORT_COLS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [SORT_COLS_N49] ON [dbo].[SORT_COLS]
(
	[SD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [TAB_COL_STATS_IDX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TAB_COL_STATS_IDX] ON [dbo].[TAB_COL_STATS]
(
	[CAT_NAME] ASC,
	[DB_NAME] ASC,
	[TABLE_NAME] ASC,
	[COLUMN_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [TAB_COL_STATS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TAB_COL_STATS_N49] ON [dbo].[TAB_COL_STATS]
(
	[TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [TABLE_PARAMS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TABLE_PARAMS_N49] ON [dbo].[TABLE_PARAMS]
(
	[TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [TABLECOLUMNPRIVILEGEINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TABLECOLUMNPRIVILEGEINDEX] ON [dbo].[TBL_COL_PRIVS]
(
	[AUTHORIZER] ASC,
	[TBL_ID] ASC,
	[COLUMN_NAME] ASC,
	[PRINCIPAL_NAME] ASC,
	[PRINCIPAL_TYPE] ASC,
	[TBL_COL_PRIV] ASC,
	[GRANTOR] ASC,
	[GRANTOR_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [TBL_COL_PRIVS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TBL_COL_PRIVS_N49] ON [dbo].[TBL_COL_PRIVS]
(
	[TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [TABLEPRIVILEGEINDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TABLEPRIVILEGEINDEX] ON [dbo].[TBL_PRIVS]
(
	[AUTHORIZER] ASC,
	[TBL_ID] ASC,
	[PRINCIPAL_NAME] ASC,
	[PRINCIPAL_TYPE] ASC,
	[TBL_PRIV] ASC,
	[GRANTOR] ASC,
	[GRANTOR_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [TBL_PRIVS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TBL_PRIVS_N49] ON [dbo].[TBL_PRIVS]
(
	[TBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [TBLS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TBLS_N49] ON [dbo].[TBLS]
(
	[DB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [TBLS_N50]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TBLS_N50] ON [dbo].[TBLS]
(
	[SD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUETABLE]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUETABLE] ON [dbo].[TBLS]
(
	[TBL_NAME] ASC,
	[DB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [TC_TXNID_INDEX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TC_TXNID_INDEX] ON [dbo].[TXN_COMPONENTS]
(
	[TC_TXNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [TBL_TO_TXN_ID_IDX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [TBL_TO_TXN_ID_IDX] ON [dbo].[TXN_TO_WRITE_ID]
(
	[T2W_DATABASE] ASC,
	[T2W_TABLE] ASC,
	[T2W_TXNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [TBL_TO_WRITE_ID_IDX]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [TBL_TO_WRITE_ID_IDX] ON [dbo].[TXN_TO_WRITE_ID]
(
	[T2W_DATABASE] ASC,
	[T2W_TABLE] ASC,
	[T2W_WRITEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [TYPE_FIELDS_N49]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE NONCLUSTERED INDEX [TYPE_FIELDS_N49] ON [dbo].[TYPE_FIELDS]
(
	[TYPE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUETYPE]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUETYPE] ON [dbo].[TYPES]
(
	[TYPE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUE_WM_MAPPING]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUE_WM_MAPPING] ON [dbo].[WM_MAPPING]
(
	[RP_ID] ASC,
	[ENTITY_TYPE] ASC,
	[ENTITY_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUE_WM_POOL]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUE_WM_POOL] ON [dbo].[WM_POOL]
(
	[RP_ID] ASC,
	[PATH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUE_WM_RESOURCEPLAN]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUE_WM_RESOURCEPLAN] ON [dbo].[WM_RESOURCEPLAN]
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUE_WM_TRIGGER]    Script Date: 11/24/2019 1:25:29 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUE_WM_TRIGGER] ON [dbo].[WM_TRIGGER]
(
	[RP_ID] ASC,
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPLETED_TXN_COMPONENTS] ADD  DEFAULT (getdate()) FOR [CTC_TIMESTAMP]
GO
ALTER TABLE [dbo].[PARTITIONS] ADD  DEFAULT ((0)) FOR [WRITE_ID]
GO
ALTER TABLE [dbo].[TBLS] ADD  DEFAULT ((0)) FOR [IS_REWRITE_ENABLED]
GO
ALTER TABLE [dbo].[TBLS] ADD  DEFAULT ((0)) FOR [WRITE_ID]
GO
ALTER TABLE [dbo].[WM_TRIGGER] ADD  DEFAULT ((0)) FOR [IS_IN_UNMANAGED]
GO
ALTER TABLE [dbo].[BUCKETING_COLS]  WITH CHECK ADD  CONSTRAINT [BUCKETING_COLS_FK1] FOREIGN KEY([SD_ID])
REFERENCES [dbo].[SDS] ([SD_ID])
GO
ALTER TABLE [dbo].[BUCKETING_COLS] CHECK CONSTRAINT [BUCKETING_COLS_FK1]
GO
ALTER TABLE [dbo].[COLUMNS_V2]  WITH CHECK ADD  CONSTRAINT [COLUMNS_V2_FK1] FOREIGN KEY([CD_ID])
REFERENCES [dbo].[CDS] ([CD_ID])
GO
ALTER TABLE [dbo].[COLUMNS_V2] CHECK CONSTRAINT [COLUMNS_V2_FK1]
GO
ALTER TABLE [dbo].[DATABASE_PARAMS]  WITH CHECK ADD  CONSTRAINT [DATABASE_PARAMS_FK1] FOREIGN KEY([DB_ID])
REFERENCES [dbo].[DBS] ([DB_ID])
GO
ALTER TABLE [dbo].[DATABASE_PARAMS] CHECK CONSTRAINT [DATABASE_PARAMS_FK1]
GO
ALTER TABLE [dbo].[DB_PRIVS]  WITH CHECK ADD  CONSTRAINT [DB_PRIVS_FK1] FOREIGN KEY([DB_ID])
REFERENCES [dbo].[DBS] ([DB_ID])
GO
ALTER TABLE [dbo].[DB_PRIVS] CHECK CONSTRAINT [DB_PRIVS_FK1]
GO
ALTER TABLE [dbo].[DBS]  WITH CHECK ADD  CONSTRAINT [DBS_FK1] FOREIGN KEY([CTLG_NAME])
REFERENCES [dbo].[CTLGS] ([NAME])
GO
ALTER TABLE [dbo].[DBS] CHECK CONSTRAINT [DBS_FK1]
GO
ALTER TABLE [dbo].[FUNC_RU]  WITH CHECK ADD  CONSTRAINT [FUNC_RU_FK1] FOREIGN KEY([FUNC_ID])
REFERENCES [dbo].[FUNCS] ([FUNC_ID])
GO
ALTER TABLE [dbo].[FUNC_RU] CHECK CONSTRAINT [FUNC_RU_FK1]
GO
ALTER TABLE [dbo].[FUNCS]  WITH CHECK ADD  CONSTRAINT [FUNCS_FK1] FOREIGN KEY([DB_ID])
REFERENCES [dbo].[DBS] ([DB_ID])
GO
ALTER TABLE [dbo].[FUNCS] CHECK CONSTRAINT [FUNCS_FK1]
GO
ALTER TABLE [dbo].[I_SCHEMA]  WITH CHECK ADD FOREIGN KEY([DB_ID])
REFERENCES [dbo].[DBS] ([DB_ID])
GO
ALTER TABLE [dbo].[IDXS]  WITH CHECK ADD  CONSTRAINT [IDXS_FK1] FOREIGN KEY([INDEX_TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[IDXS] CHECK CONSTRAINT [IDXS_FK1]
GO
ALTER TABLE [dbo].[IDXS]  WITH CHECK ADD  CONSTRAINT [IDXS_FK2] FOREIGN KEY([SD_ID])
REFERENCES [dbo].[SDS] ([SD_ID])
GO
ALTER TABLE [dbo].[IDXS] CHECK CONSTRAINT [IDXS_FK2]
GO
ALTER TABLE [dbo].[IDXS]  WITH CHECK ADD  CONSTRAINT [IDXS_FK3] FOREIGN KEY([ORIG_TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[IDXS] CHECK CONSTRAINT [IDXS_FK3]
GO
ALTER TABLE [dbo].[INDEX_PARAMS]  WITH CHECK ADD  CONSTRAINT [INDEX_PARAMS_FK1] FOREIGN KEY([INDEX_ID])
REFERENCES [dbo].[IDXS] ([INDEX_ID])
GO
ALTER TABLE [dbo].[INDEX_PARAMS] CHECK CONSTRAINT [INDEX_PARAMS_FK1]
GO
ALTER TABLE [dbo].[KEY_CONSTRAINTS]  WITH CHECK ADD  CONSTRAINT [KEY_CONSTRAINTS_FK1] FOREIGN KEY([CHILD_CD_ID])
REFERENCES [dbo].[CDS] ([CD_ID])
GO
ALTER TABLE [dbo].[KEY_CONSTRAINTS] CHECK CONSTRAINT [KEY_CONSTRAINTS_FK1]
GO
ALTER TABLE [dbo].[KEY_CONSTRAINTS]  WITH CHECK ADD  CONSTRAINT [KEY_CONSTRAINTS_FK2] FOREIGN KEY([CHILD_TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[KEY_CONSTRAINTS] CHECK CONSTRAINT [KEY_CONSTRAINTS_FK2]
GO
ALTER TABLE [dbo].[KEY_CONSTRAINTS]  WITH CHECK ADD  CONSTRAINT [KEY_CONSTRAINTS_FK3] FOREIGN KEY([PARENT_CD_ID])
REFERENCES [dbo].[CDS] ([CD_ID])
GO
ALTER TABLE [dbo].[KEY_CONSTRAINTS] CHECK CONSTRAINT [KEY_CONSTRAINTS_FK3]
GO
ALTER TABLE [dbo].[KEY_CONSTRAINTS]  WITH CHECK ADD  CONSTRAINT [KEY_CONSTRAINTS_FK4] FOREIGN KEY([PARENT_TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[KEY_CONSTRAINTS] CHECK CONSTRAINT [KEY_CONSTRAINTS_FK4]
GO
ALTER TABLE [dbo].[MV_TABLES_USED]  WITH CHECK ADD FOREIGN KEY([MV_CREATION_METADATA_ID])
REFERENCES [dbo].[MV_CREATION_METADATA] ([MV_CREATION_METADATA_ID])
GO
ALTER TABLE [dbo].[MV_TABLES_USED]  WITH CHECK ADD FOREIGN KEY([TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[PART_COL_PRIVS]  WITH CHECK ADD  CONSTRAINT [PART_COL_PRIVS_FK1] FOREIGN KEY([PART_ID])
REFERENCES [dbo].[PARTITIONS] ([PART_ID])
GO
ALTER TABLE [dbo].[PART_COL_PRIVS] CHECK CONSTRAINT [PART_COL_PRIVS_FK1]
GO
ALTER TABLE [dbo].[PART_COL_STATS]  WITH CHECK ADD  CONSTRAINT [PART_COL_STATS_FK1] FOREIGN KEY([PART_ID])
REFERENCES [dbo].[PARTITIONS] ([PART_ID])
GO
ALTER TABLE [dbo].[PART_COL_STATS] CHECK CONSTRAINT [PART_COL_STATS_FK1]
GO
ALTER TABLE [dbo].[PART_PRIVS]  WITH CHECK ADD  CONSTRAINT [PART_PRIVS_FK1] FOREIGN KEY([PART_ID])
REFERENCES [dbo].[PARTITIONS] ([PART_ID])
GO
ALTER TABLE [dbo].[PART_PRIVS] CHECK CONSTRAINT [PART_PRIVS_FK1]
GO
ALTER TABLE [dbo].[PARTITION_KEY_VALS]  WITH CHECK ADD  CONSTRAINT [PARTITION_KEY_VALS_FK1] FOREIGN KEY([PART_ID])
REFERENCES [dbo].[PARTITIONS] ([PART_ID])
GO
ALTER TABLE [dbo].[PARTITION_KEY_VALS] CHECK CONSTRAINT [PARTITION_KEY_VALS_FK1]
GO
ALTER TABLE [dbo].[PARTITION_KEYS]  WITH CHECK ADD  CONSTRAINT [PARTITION_KEYS_FK1] FOREIGN KEY([TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[PARTITION_KEYS] CHECK CONSTRAINT [PARTITION_KEYS_FK1]
GO
ALTER TABLE [dbo].[PARTITION_PARAMS]  WITH CHECK ADD  CONSTRAINT [PARTITION_PARAMS_FK1] FOREIGN KEY([PART_ID])
REFERENCES [dbo].[PARTITIONS] ([PART_ID])
GO
ALTER TABLE [dbo].[PARTITION_PARAMS] CHECK CONSTRAINT [PARTITION_PARAMS_FK1]
GO
ALTER TABLE [dbo].[PARTITIONS]  WITH CHECK ADD  CONSTRAINT [PARTITIONS_FK1] FOREIGN KEY([TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[PARTITIONS] CHECK CONSTRAINT [PARTITIONS_FK1]
GO
ALTER TABLE [dbo].[PARTITIONS]  WITH CHECK ADD  CONSTRAINT [PARTITIONS_FK2] FOREIGN KEY([SD_ID])
REFERENCES [dbo].[SDS] ([SD_ID])
GO
ALTER TABLE [dbo].[PARTITIONS] CHECK CONSTRAINT [PARTITIONS_FK2]
GO
ALTER TABLE [dbo].[ROLE_MAP]  WITH CHECK ADD  CONSTRAINT [ROLE_MAP_FK1] FOREIGN KEY([ROLE_ID])
REFERENCES [dbo].[ROLES] ([ROLE_ID])
GO
ALTER TABLE [dbo].[ROLE_MAP] CHECK CONSTRAINT [ROLE_MAP_FK1]
GO
ALTER TABLE [dbo].[SCHEMA_VERSION]  WITH CHECK ADD FOREIGN KEY([CD_ID])
REFERENCES [dbo].[CDS] ([CD_ID])
GO
ALTER TABLE [dbo].[SCHEMA_VERSION]  WITH CHECK ADD FOREIGN KEY([SCHEMA_ID])
REFERENCES [dbo].[I_SCHEMA] ([SCHEMA_ID])
GO
ALTER TABLE [dbo].[SCHEMA_VERSION]  WITH CHECK ADD FOREIGN KEY([SERDE_ID])
REFERENCES [dbo].[SERDES] ([SERDE_ID])
GO
ALTER TABLE [dbo].[SD_PARAMS]  WITH CHECK ADD  CONSTRAINT [SD_PARAMS_FK1] FOREIGN KEY([SD_ID])
REFERENCES [dbo].[SDS] ([SD_ID])
GO
ALTER TABLE [dbo].[SD_PARAMS] CHECK CONSTRAINT [SD_PARAMS_FK1]
GO
ALTER TABLE [dbo].[SDS]  WITH CHECK ADD  CONSTRAINT [SDS_FK1] FOREIGN KEY([SERDE_ID])
REFERENCES [dbo].[SERDES] ([SERDE_ID])
GO
ALTER TABLE [dbo].[SDS] CHECK CONSTRAINT [SDS_FK1]
GO
ALTER TABLE [dbo].[SDS]  WITH CHECK ADD  CONSTRAINT [SDS_FK2] FOREIGN KEY([CD_ID])
REFERENCES [dbo].[CDS] ([CD_ID])
GO
ALTER TABLE [dbo].[SDS] CHECK CONSTRAINT [SDS_FK2]
GO
ALTER TABLE [dbo].[SERDE_PARAMS]  WITH CHECK ADD  CONSTRAINT [SERDE_PARAMS_FK1] FOREIGN KEY([SERDE_ID])
REFERENCES [dbo].[SERDES] ([SERDE_ID])
GO
ALTER TABLE [dbo].[SERDE_PARAMS] CHECK CONSTRAINT [SERDE_PARAMS_FK1]
GO
ALTER TABLE [dbo].[SKEWED_COL_NAMES]  WITH CHECK ADD  CONSTRAINT [SKEWED_COL_NAMES_FK1] FOREIGN KEY([SD_ID])
REFERENCES [dbo].[SDS] ([SD_ID])
GO
ALTER TABLE [dbo].[SKEWED_COL_NAMES] CHECK CONSTRAINT [SKEWED_COL_NAMES_FK1]
GO
ALTER TABLE [dbo].[SKEWED_COL_VALUE_LOC_MAP]  WITH CHECK ADD  CONSTRAINT [SKEWED_COL_VALUE_LOC_MAP_FK1] FOREIGN KEY([SD_ID])
REFERENCES [dbo].[SDS] ([SD_ID])
GO
ALTER TABLE [dbo].[SKEWED_COL_VALUE_LOC_MAP] CHECK CONSTRAINT [SKEWED_COL_VALUE_LOC_MAP_FK1]
GO
ALTER TABLE [dbo].[SKEWED_COL_VALUE_LOC_MAP]  WITH CHECK ADD  CONSTRAINT [SKEWED_COL_VALUE_LOC_MAP_FK2] FOREIGN KEY([STRING_LIST_ID_KID])
REFERENCES [dbo].[SKEWED_STRING_LIST] ([STRING_LIST_ID])
GO
ALTER TABLE [dbo].[SKEWED_COL_VALUE_LOC_MAP] CHECK CONSTRAINT [SKEWED_COL_VALUE_LOC_MAP_FK2]
GO
ALTER TABLE [dbo].[SKEWED_STRING_LIST_VALUES]  WITH CHECK ADD  CONSTRAINT [SKEWED_STRING_LIST_VALUES_FK1] FOREIGN KEY([STRING_LIST_ID])
REFERENCES [dbo].[SKEWED_STRING_LIST] ([STRING_LIST_ID])
GO
ALTER TABLE [dbo].[SKEWED_STRING_LIST_VALUES] CHECK CONSTRAINT [SKEWED_STRING_LIST_VALUES_FK1]
GO
ALTER TABLE [dbo].[SKEWED_VALUES]  WITH CHECK ADD  CONSTRAINT [SKEWED_VALUES_FK1] FOREIGN KEY([SD_ID_OID])
REFERENCES [dbo].[SDS] ([SD_ID])
GO
ALTER TABLE [dbo].[SKEWED_VALUES] CHECK CONSTRAINT [SKEWED_VALUES_FK1]
GO
ALTER TABLE [dbo].[SKEWED_VALUES]  WITH CHECK ADD  CONSTRAINT [SKEWED_VALUES_FK2] FOREIGN KEY([STRING_LIST_ID_EID])
REFERENCES [dbo].[SKEWED_STRING_LIST] ([STRING_LIST_ID])
GO
ALTER TABLE [dbo].[SKEWED_VALUES] CHECK CONSTRAINT [SKEWED_VALUES_FK2]
GO
ALTER TABLE [dbo].[SORT_COLS]  WITH CHECK ADD  CONSTRAINT [SORT_COLS_FK1] FOREIGN KEY([SD_ID])
REFERENCES [dbo].[SDS] ([SD_ID])
GO
ALTER TABLE [dbo].[SORT_COLS] CHECK CONSTRAINT [SORT_COLS_FK1]
GO
ALTER TABLE [dbo].[TAB_COL_STATS]  WITH CHECK ADD  CONSTRAINT [TAB_COL_STATS_FK1] FOREIGN KEY([TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[TAB_COL_STATS] CHECK CONSTRAINT [TAB_COL_STATS_FK1]
GO
ALTER TABLE [dbo].[TABLE_PARAMS]  WITH CHECK ADD  CONSTRAINT [TABLE_PARAMS_FK1] FOREIGN KEY([TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[TABLE_PARAMS] CHECK CONSTRAINT [TABLE_PARAMS_FK1]
GO
ALTER TABLE [dbo].[TBL_COL_PRIVS]  WITH CHECK ADD  CONSTRAINT [TBL_COL_PRIVS_FK1] FOREIGN KEY([TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[TBL_COL_PRIVS] CHECK CONSTRAINT [TBL_COL_PRIVS_FK1]
GO
ALTER TABLE [dbo].[TBL_PRIVS]  WITH CHECK ADD  CONSTRAINT [TBL_PRIVS_FK1] FOREIGN KEY([TBL_ID])
REFERENCES [dbo].[TBLS] ([TBL_ID])
GO
ALTER TABLE [dbo].[TBL_PRIVS] CHECK CONSTRAINT [TBL_PRIVS_FK1]
GO
ALTER TABLE [dbo].[TBLS]  WITH CHECK ADD  CONSTRAINT [TBLS_FK1] FOREIGN KEY([DB_ID])
REFERENCES [dbo].[DBS] ([DB_ID])
GO
ALTER TABLE [dbo].[TBLS] CHECK CONSTRAINT [TBLS_FK1]
GO
ALTER TABLE [dbo].[TBLS]  WITH CHECK ADD  CONSTRAINT [TBLS_FK2] FOREIGN KEY([SD_ID])
REFERENCES [dbo].[SDS] ([SD_ID])
GO
ALTER TABLE [dbo].[TBLS] CHECK CONSTRAINT [TBLS_FK2]
GO
ALTER TABLE [dbo].[TXN_COMPONENTS]  WITH CHECK ADD FOREIGN KEY([TC_TXNID])
REFERENCES [dbo].[TXNS] ([TXN_ID])
GO
ALTER TABLE [dbo].[TYPE_FIELDS]  WITH CHECK ADD  CONSTRAINT [TYPE_FIELDS_FK1] FOREIGN KEY([TYPE_NAME])
REFERENCES [dbo].[TYPES] ([TYPES_ID])
GO
ALTER TABLE [dbo].[TYPE_FIELDS] CHECK CONSTRAINT [TYPE_FIELDS_FK1]
GO
ALTER TABLE [dbo].[WM_MAPPING]  WITH CHECK ADD  CONSTRAINT [WM_MAPPING_FK1] FOREIGN KEY([RP_ID])
REFERENCES [dbo].[WM_RESOURCEPLAN] ([RP_ID])
GO
ALTER TABLE [dbo].[WM_MAPPING] CHECK CONSTRAINT [WM_MAPPING_FK1]
GO
ALTER TABLE [dbo].[WM_POOL]  WITH CHECK ADD  CONSTRAINT [WM_POOL_FK1] FOREIGN KEY([RP_ID])
REFERENCES [dbo].[WM_RESOURCEPLAN] ([RP_ID])
GO
ALTER TABLE [dbo].[WM_POOL] CHECK CONSTRAINT [WM_POOL_FK1]
GO
ALTER TABLE [dbo].[WM_POOL_TO_TRIGGER]  WITH CHECK ADD  CONSTRAINT [WM_POOL_TO_TRIGGER_FK1] FOREIGN KEY([POOL_ID])
REFERENCES [dbo].[WM_POOL] ([POOL_ID])
GO
ALTER TABLE [dbo].[WM_POOL_TO_TRIGGER] CHECK CONSTRAINT [WM_POOL_TO_TRIGGER_FK1]
GO
ALTER TABLE [dbo].[WM_POOL_TO_TRIGGER]  WITH CHECK ADD  CONSTRAINT [WM_POOL_TO_TRIGGER_FK2] FOREIGN KEY([TRIGGER_ID])
REFERENCES [dbo].[WM_TRIGGER] ([TRIGGER_ID])
GO
ALTER TABLE [dbo].[WM_POOL_TO_TRIGGER] CHECK CONSTRAINT [WM_POOL_TO_TRIGGER_FK2]
GO
ALTER TABLE [dbo].[WM_RESOURCEPLAN]  WITH CHECK ADD  CONSTRAINT [WM_RESOURCEPLAN_FK1] FOREIGN KEY([DEFAULT_POOL_ID])
REFERENCES [dbo].[WM_POOL] ([POOL_ID])
GO
ALTER TABLE [dbo].[WM_RESOURCEPLAN] CHECK CONSTRAINT [WM_RESOURCEPLAN_FK1]
GO
ALTER TABLE [dbo].[WM_TRIGGER]  WITH CHECK ADD  CONSTRAINT [WM_TRIGGER_FK1] FOREIGN KEY([RP_ID])
REFERENCES [dbo].[WM_RESOURCEPLAN] ([RP_ID])
GO
ALTER TABLE [dbo].[WM_TRIGGER] CHECK CONSTRAINT [WM_TRIGGER_FK1]
GO
ALTER TABLE [dbo].[DB_PRIVS]  WITH CHECK ADD CHECK  (([GRANT_OPTION]=(1) OR [GRANT_OPTION]=(0)))
GO
ALTER TABLE [dbo].[GLOBAL_PRIVS]  WITH CHECK ADD CHECK  (([GRANT_OPTION]=(1) OR [GRANT_OPTION]=(0)))
GO
ALTER TABLE [dbo].[PART_COL_PRIVS]  WITH CHECK ADD CHECK  (([GRANT_OPTION]=(1) OR [GRANT_OPTION]=(0)))
GO
ALTER TABLE [dbo].[PART_PRIVS]  WITH CHECK ADD CHECK  (([GRANT_OPTION]=(1) OR [GRANT_OPTION]=(0)))
GO
ALTER TABLE [dbo].[ROLE_MAP]  WITH CHECK ADD CHECK  (([GRANT_OPTION]=(1) OR [GRANT_OPTION]=(0)))
GO
ALTER TABLE [dbo].[TBL_COL_PRIVS]  WITH CHECK ADD CHECK  (([GRANT_OPTION]=(1) OR [GRANT_OPTION]=(0)))
GO
ALTER TABLE [dbo].[TBL_PRIVS]  WITH CHECK ADD CHECK  (([GRANT_OPTION]=(1) OR [GRANT_OPTION]=(0)))
GO
